fix(mmio): use TBO for ramToLimb inst
Consensys/besu-sequencer-plugins pull request #1256
Opened 2024-09-20 07:10 UTC by letypequividelespoubelles

2024-09-20 18:26 UTC, OlivierBBB requested changes
The `checkArguments` may catch mistakes.

2024-09-20 18:26 UTC, OlivierBBB commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      final short targetByteOffsetTrigger,
What's the reason for the `Trigger` terminology ?

2024-09-20 18:26 UTC, OlivierBBB commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      bit3.add(ct, plateau(targetByteOffsetTrigger + size, ct));
In the spec we write some preconditions that we should add here.

2024-09-20 18:26 UTC, OlivierBBB commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioPatterns.java
> -
Were these methods redundant ?

2024-09-20 18:26 UTC, OlivierBBB commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      bit3.add(ct, plateau(targetByteOffsetTrigger + size, ct));
For `[1 => 1 Padded]`
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/f3b35aab-f433-415b-a779-ecc17ee59097">

2024-09-20 18:26 UTC, OlivierBBB commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      bit4.add(ct, plateau(targetOffsetTrigger + size, ct));
Similarly here for `[2 => 1 Padded]`
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/c6169415-7b3f-40c1-a6c1-0119667b17ba">

2024-09-21 08:30 UTC, letypequividelespoubelles commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      final short targetByteOffsetTrigger,
no reason, just historic from the go implem I guess. The name in the spec is BlaMarker which is not ideal neither

2024-09-21 08:37 UTC, letypequividelespoubelles commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      bit3.add(ct, plateau(targetByteOffsetTrigger + size, ct));
checkArgument added

2024-09-21 08:38 UTC, letypequividelespoubelles commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioPatterns.java
> -
no, just unused and wrong method

2024-09-21 08:38 UTC, letypequividelespoubelles commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      bit4.add(ct, plateau(targetOffsetTrigger + size, ct));
checkArgument added

2024-09-21 09:06 UTC, OlivierBBB commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java
> +      final short targetByteOffsetTrigger,
I may just change these to become byte offsets in the spec rather than markers.

2024-09-21 10:02 UTC, OlivierBBB approved these changes
LGTM

2024-09-21 10:02 UTC, merged