Fix: adding the `chainId` to the HUB and BLOCK_DATA modules
Consensys/besu-sequencer-plugins pull request #1359
Opened 2024-10-02 16:36 UTC by OlivierBBB

2024-10-02 21:29 UTC, OlivierBBB commented on arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java
> +    BigInteger nonnegativeChainId = chainId.abs();
For some reason the chainId sometimes gets interpreted as a negative integer.

2024-10-03 05:06 UTC, letypequividelespoubelles requested changes
It's fixing the referenceTest, but we still don't get the chainId from Besu in prod, so now it'll be broken.

2024-10-03 06:24 UTC, letypequividelespoubelles commented on arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java
> +    this.chainId = nonnegativeChainId;
we just need to give it to the HUB, no need to keep it in the ZkTracer

2024-10-03 12:35 UTC, letypequividelespoubelles approved these changes
Please address comment in a future PR

2024-10-03 12:56 UTC, merged