Fix/getaccount
Consensys/besu-sequencer-plugins pull request #1493
Opened 2024-11-11 04:36 UTC by FlorianHuc

remove tracking as side effect

2024-11-16 07:40 UTC, letypequividelespoubelles requested changes
LGTM except the update of the constraints ;)

2024-11-23 09:49 UTC, OlivierBBB commented
@FlorianHuc What tracking do you mean ?

2024-11-23 09:50 UTC, OlivierBBB approved these changes

2024-11-26 12:46 UTC, letypequividelespoubelles approved these changes
LGTM

2024-11-26 13:02 UTC, merged