feat: add mechanism to count rows not yet in traced operation
Consensys/besu-sequencer-plugins pull request #699
Opened 2024-05-03 12:23 UTC by letypequividelespoubelles

2024-05-03 15:41 UTC, ahamlat requested changes
Does it make sens to store the additional lines as additionalRows grow to avoid, iterating over it when calculating line counting ?

2024-05-03 15:41 UTC, ahamlat commented on arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/Wcp.java
> +  public final Stack<Integer> additionalRows = new Stack<>();
Consider using `Deque<Integer> stack = new ArrayDeque<>();`, Stack extends Vector, thus not efficient at all.

2024-05-06 03:20 UTC, letypequividelespoubelles commented
> Does it make sens to store the additional lines as additionalRows grow to avoid iterating over it when calculating line counting ?

yes absolutely it does, done.

2024-05-07 08:56 UTC, powerslider approved these changes

2024-05-07 09:51 UTC, ahamlat approved these changes
LGTM

2024-05-07 09:52 UTC, merged